version: '{build}-{branch}'

install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install
  - choco install chocolatey-core.extension
  - choco pack
  - choco install -y cloud-screen-resolution --params "'/width:1366 /height:768 /password:appveyor!Abc9'" -d -s .

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

artifacts:
  - path: '*.nupkg'
    name: 'Cloud Screen Resolution'
